### PR TITLE
fix: declarations may become undefined

### PR DESCRIPTION
**Pull request by ericfong**

### CODE REVIEW

**Comment by bclinkinbeard** [comment]
How does that end up being the case? If it's a valid scenario, I think I'd prefer to just terminate early via `if (!declarations) return;`

**Comment by ericfong** [comment]
Basically a fix for #2 , we can change that to if (!declarations) return;

**Comment by bclinkinbeard** [comment]
Cool. If you want to update the PR I will merge and publish

**Comment by ericfong** [comment]
Done! 

rework-assets also depend on this module, which also block my webpack sass building

**Comment by bclinkinbeard** [comment]
Landed as https://github.com/reworkcss/rework-plugin-function/commit/251381a7736cecfaca3290f2b76570d6338c7ed6, published as 1.0.2

Thanks!

**Pull request closed without merging**
